# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '960267c8-1b22-4a40-b4a5-919f5cc1f7ef'
  imageRepository: 'alxchvmulticontainerwordpresskub'
  containerRegistry: 'containerizedsiteacr.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'containerizedsiteacr16603a83-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DockerCompose@0
      displayName: Build and push an image to container registry
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure subscription 1 (2c780a18-ca02-4f44-8e4c-153057104a63)'
        azureContainerRegistry: '{"loginServer":"containerizedsiteacr.azurecr.io", "id" : "/subscriptions/2c780a18-ca02-4f44-8e4c-153057104a63/resourceGroups/containerized-site-rg/providers/Microsoft.ContainerRegistry/registries/containerizedsiteacr"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'


